/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CompleteRegistrationRouteImport } from './routes/complete-registration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SuccessfulLoginRouteImport } from './routes/successful-login'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as UtilsCheckCookieRouteImport } from './routes/_utils/check-cookie'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CompleteRegistrationRoute = CompleteRegistrationRouteImport.update({
  id: '/complete-registration',
  path: '/complete-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessfulLoginRoute = SuccessfulLoginRouteImport.update({
  id: '/successful-login',
  path: '/successful-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const UtilsCheckCookieRoute = UtilsCheckCookieRouteImport.update({
  id: '/_utils/check-cookie',
  path: '/check-cookie',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/about': typeof AboutRoute
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successful-login': typeof SuccessfulLoginRoute
  '/check-cookie': typeof UtilsCheckCookieRoute
}
export interface FileRoutesByTo {
  '/about': typeof AboutRoute
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successful-login': typeof SuccessfulLoginRoute
  '/check-cookie': typeof UtilsCheckCookieRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/about': typeof AboutRoute
  '/complete-registration': typeof CompleteRegistrationRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/successful-login': typeof SuccessfulLoginRoute
  '/_utils/check-cookie': typeof UtilsCheckCookieRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/complete-registration'
    | '/login'
    | '/register'
    | '/successful-login'
    | '/check-cookie'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/complete-registration'
    | '/login'
    | '/register'
    | '/successful-login'
    | '/check-cookie'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/about'
    | '/complete-registration'
    | '/login'
    | '/register'
    | '/successful-login'
    | '/_utils/check-cookie'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  AboutRoute: typeof AboutRoute
  CompleteRegistrationRoute: typeof CompleteRegistrationRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  SuccessfulLoginRoute: typeof SuccessfulLoginRoute
  UtilsCheckCookieRoute: typeof UtilsCheckCookieRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complete-registration': {
      id: '/complete-registration'
      path: '/complete-registration'
      fullPath: '/complete-registration'
      preLoaderRoute: typeof CompleteRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/successful-login': {
      id: '/successful-login'
      path: '/successful-login'
      fullPath: '/successful-login'
      preLoaderRoute: typeof SuccessfulLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_utils/check-cookie': {
      id: '/_utils/check-cookie'
      path: '/check-cookie'
      fullPath: '/check-cookie'
      preLoaderRoute: typeof UtilsCheckCookieRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  AboutRoute: AboutRoute,
  CompleteRegistrationRoute: CompleteRegistrationRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  SuccessfulLoginRoute: SuccessfulLoginRoute,
  UtilsCheckCookieRoute: UtilsCheckCookieRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
